

env:
  node: true
  commonjs: true
  es2021: true
  browser: true
extends: 
  - eslint:recommended
  - plugin:eslint-plugin-react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect 
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  eqeqeq: error
  no-trailing-spaces: error
  object-curly-spacing:
    - error
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  no-console: 0
