POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "Mark",
  "password": "123",
  "email": "mark_01@gmail.com"
}

###
POST http://localhost:5000/api/users/8f240474-d09b-41a1-a889-2db908e0085f
Content-Type: application/json

{
  "method": "gcash",
  "reference": "09231407456"
}

###
GET http://localhost:5000/api/users/8f240474-d09b-41a1-a889-2db908e0085f

###
GET http://localhost:5000/api/users